worker:
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  config:
    workPool: ${prefect_work_pool}
    limit: 8
    prefetchSeconds: 30
    baseJobTemplate:
      configuration: |
        {
          "variables": {
            "type": "object",
            "properties": {
              "env": {
                "type": "object",
                "title": "Environment Variables",
                "description": "Environment variables to set when starting a flow run.",
                "additionalProperties": {
                  "anyOf": [
                    {
                      "type": "string"
                    },
                    {
                      "type": "null"
                    }
                  ]
                }
              },
              "secretName": {
                "type": "string",
                "title": "Secret Name",
                "default": "${envs_secret_name}",
                "description": "The name of the Kubernetes secret to load as environment variables."
              },
              "name": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "null"
                  }
                ],
                "title": "Name",
                "default": null,
                "description": "Name given to infrastructure created by a worker."
              },
              "image": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "null"
                  }
                ],
                "title": "Image",
                "default": null,
                "examples": [
                  "docker.io/prefecthq/prefect:3-latest"
                ],
                "description": "The image reference of a container image to use for created jobs. If not set, the latest Prefect image will be used."
              },
              "labels": {
                "type": "object",
                "title": "Labels",
                "description": "Labels applied to infrastructure created by a worker.",
                "additionalProperties": {
                  "type": "string"
                }
              },
              "command": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "null"
                  }
                ],
                "title": "Command",
                "default": null,
                "description": "The command to use when starting a flow run. In most cases, this should be left blank and the command will be automatically generated by the worker."
              },
              "namespace": {
                "type": "string",
                "title": "Namespace",
                "default": "${prefect_worker_namespace}",
                "description": "The Kubernetes namespace to create jobs within."
              },
              "backoff_limit": {
                "type": "integer",
                "title": "Backoff Limit",
                "default": 0,
                "minimum": 0,
                "description": "The number of times Kubernetes will retry a job after pod eviction. If set to 0, Prefect will reschedule the flow run when the pod is evicted."
              },
              "stream_output": {
                "type": "boolean",
                "title": "Stream Output",
                "default": true,
                "description": "If set, output will be streamed from the job to local standard output."
              },
              "cluster_config": {
                "anyOf": [
                  {
                    "$ref": "#/definitions/KubernetesClusterConfig"
                  },
                  {
                    "type": "null"
                  }
                ],
                "default": null,
                "description": "The Kubernetes cluster config to use for job creation."
              },
              "finished_job_ttl": {
                "anyOf": [
                  {
                    "type": "integer"
                  },
                  {
                    "type": "null"
                  }
                ],
                "title": "Finished Job TTL",
                "default": null,
                "description": "The number of seconds to retain jobs after completion. If set, finished jobs will be cleaned up by Kubernetes after the given delay. If not set, jobs will be retained indefinitely."
              },
              "image_pull_policy": {
                "enum": [
                  "IfNotPresent",
                  "Always",
                  "Never"
                ],
                "type": "string",
                "title": "Image Pull Policy",
                "default": "IfNotPresent",
                "description": "The Kubernetes image pull policy to use for job containers."
              },
              "service_account_name": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "null"
                  }
                ],
                "title": "Service Account Name",
                "default": null,
                "description": "The Kubernetes service account to use for job creation."
              },
              "job_watch_timeout_seconds": {
                "anyOf": [
                  {
                    "type": "integer"
                  },
                  {
                    "type": "null"
                  }
                ],
                "title": "Job Watch Timeout Seconds",
                "default": null,
                "description": "Number of seconds to wait for each event emitted by a job before timing out. If not set, the worker will wait for each event indefinitely."
              },
              "pod_watch_timeout_seconds": {
                "type": "integer",
                "title": "Pod Watch Timeout Seconds",
                "default": 60,
                "description": "Number of seconds to watch for pod creation before timing out."
              }
            },
            "definitions": {
              "KubernetesClusterConfig": {
                "type": "object",
                "title": "KubernetesClusterConfig",
                "required": [
                  "config",
                  "context_name"
                ],
                "properties": {
                  "config": {
                    "type": "object",
                    "title": "Config",
                    "description": "The entire contents of a kubectl config file.",
                    "additionalProperties": true
                  },
                  "context_name": {
                    "type": "string",
                    "title": "Context Name",
                    "description": "The name of the kubectl context to use."
                  }
                },
                "description": "Stores configuration for interaction with Kubernetes clusters.\n\nSee `from_file` for creation.",
                "secret_fields": [],
                "block_type_slug": "kubernetes-cluster-config",
                "block_schema_references": {}
              }
            },
            "description": "Default variables for the Kubernetes worker.\n\nThe schema for this class is used to populate the `variables` section of the default\nbase job template."
          },
          "job_configuration": {
            "env": "{{ env }}",
            "name": "{{ name }}",
            "labels": "{{ labels }}",
            "command": "{{ command }}",
            "namespace": "{{ namespace }}",
            "job_manifest": {
              "kind": "Job",
              "spec": {
                "template": {
                  "spec": {
                    "containers": [
                      {
                        "env": "{{ env }}",
                        "envFrom": [
                          {
                            "secretRef": {
                              "name": "{{ secretName }}"
                            }
                          }
                        ],
                        "args": "{{ command }}",
                        "name": "prefect-job",
                        "image": "{{ image }}",
                        "imagePullPolicy": "{{ image_pull_policy }}",
                        "imagePullSecrets": [
                          {
                            "name": "${image_pull_secret_name}"
                          }
                        ]
                      }
                    ],
                    "completions": 1,
                    "parallelism": 1,
                    "restartPolicy": "Never",
                    "serviceAccountName": "{{ service_account_name }}"
                  }
                },
                "backoffLimit": "{{ backoff_limit }}",
                "ttlSecondsAfterFinished": "{{ finished_job_ttl }}"
              },
              "metadata": {
                "labels": "{{ labels }}",
                "namespace": "{{ namespace }}",
                "generateName": "{{ name }}-"
              },
              "apiVersion": "batch/v1"
            },
            "stream_output": "{{ stream_output }}",
            "cluster_config": "{{ cluster_config }}",
            "job_watch_timeout_seconds": "{{ job_watch_timeout_seconds }}",
            "pod_watch_timeout_seconds": "{{ pod_watch_timeout_seconds }}"
          }
        }

  apiConfig: selfHostedServer
  selfHostedServerApiConfig:
    apiUrl: ${prefect_server_url}

  replicaCount: 1

  resources:
    requests:
      memory: 4Gi
      cpu: 1000m
    limits:
      memory: 8Gi
      cpu: 2000m

  livenessProbe:
    enabled: true

role:
  create: true
  extraPermissions:
    - apiGroups: ["apiextensions.k8s.io"]
      resources: ["customresourcedefinitions"]
      verbs: ["get", "list", "watch"]
    - apiGroups: [""]
      resources: ["namespaces"]
      verbs: ["get", "list", "watch"]

rolebinding:
  create: true
